data-platform-master/data_platform/urls.py
from django.contrib import admin
from django.urls import path, include
from users.views import dashboard

urlpatterns = [
    path('', dashboard, name='dashboard'),
    path('workflows/', include('workflows.urls')),
    path('admin/', admin.site.urls),

    path('users/', include('users.urls')),

    path('datasets/', include('datasets.urls')),
    path('notifications/', include('notifications.urls')),
    path('notebooks/', include('notebooks.urls')),
]

data-platform-master/notebooks/urls.py
from django.urls import path
from django.urls import re_path

from . import consumers
from . import views

app_name = "notebooks"

urlpatterns = [
    # notebook crud
    path("", views.NotebooksListView.as_view(), name="index"),
    path("create/", views.NotebookCreateView.as_view(), name="create"),
    path("<int:pk>/", views.NotebookDetailView.as_view(), name="detail"),
    path("<int:pk>/delete/", views.NotebookDeleteView.as_view(), name="delete"),
    path("<int:pk>/export/", views.ExportNotebook.as_view(), name="export"),
    path("<int:pk>/restart_kernel/", views.restart_kernel_view, name="restart_kernel"),
    # cell api
    path("<int:notebook_pk>/cell/create/", views.cell_create_view, name="cell_create"),
    path("<int:notebook_pk>/cell/update/<int:cell_pk>/", views.cell_update_view, name="cell_update"),
    path("<int:notebook_pk>/cell/delete/<int:cell_pk>/", views.cell_delete_view, name="cell_delete"),
    # code snippets
    path("snippets/", views.snippets_list_view, name="snippets"),
    path("snippets/<str:name>/", views.snippet_detail_view, name="snippet_detail"),
]

websocket_urlpatterns = [
    re_path(r'ws/notebook/(?P<notebook_id>\d+)/$', consumers.NotebookConsumer.as_asgi()),
]

data-platform-master/users/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
    path('logout/', auth_views.LogoutView.as_view(template_name='registration/logout.html'), name='logout'),
    path('', include('django.contrib.auth.urls')),
    path('signup/', views.Signup.as_view(), name='signup'),
]

data-platform-master/notebooks/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _

from datasets.models import Dataset

CODE_SNIPPETS_DIR = './notebooks/static/notebooks/snippets'


class Session(models.Model):
    class SessionStatus(models.TextChoices):
        NOTRUNNING = "NR", _("Not Running")
        RUNNING = "R", _("Running")
        ENDED = "E", _("Ended")

    uuid = models.CharField(max_length=255)
    container_id = models.CharField(max_length=100, null=True)
    status = models.CharField(max_length=3, choices=SessionStatus.choices, default=SessionStatus.NOTRUNNING)
    run_counter = models.IntegerField(default=1)

    def __str__(self):
        return str(self.uuid)

class Notebook(models.Model):
    name = models.CharField(max_length=255)
    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    session = models.OneToOneField(Session, on_delete=models.CASCADE, null=True, related_name="notebook")
    accessible_datasets = models.ManyToManyField(Dataset, blank=True)

    def __str__(self):
        return str(self.name)

class Cell(models.Model):
    class CellStatus(models.TextChoices):
        RUNNING = "R", _("Running")
        DONE = "D", _("Done")
        NONE = "N", _("None")

    notebook = models.ForeignKey(Notebook, on_delete=models.CASCADE, related_name='cells', blank=True)
    code = models.TextField(null=True, blank=True)
    cell_status = models.CharField(max_length=1, choices=CellStatus.choices, default=CellStatus.NONE)

data-platform-master/notebooks/forms.py
from django.core.files.base import ContentFile
from django.forms import ModelForm
from django.shortcuts import reverse

from notebooks.models import Notebook
from notebooks.services.export import get_notebook_code
from workflows.models import Task, Secret

from workflows.models import PythonTask


class NotebookForm(ModelForm):
    def __init__(self, *args, **kwargs):
        self.creator = kwargs.pop('user')
        super().__init__(*args, **kwargs)
        self.fields['accessible_datasets'].label = 'Select the datasets this task will make use of'
        self.fields['accessible_datasets'].queryset = self.creator.datasets

    class Meta:
        model = Notebook
        fields = ['name', 'accessible_datasets']

    def save(self, commit=True):
        notebook = super().save(commit=False)
        notebook.creator = self.creator
        if commit:
            notebook.save()
            self.save_m2m()
        return notebook


class ExportNotebookForm(ModelForm):
    def __init__(self, *args, **kwargs):
        self.creator = kwargs.pop('user')
        self.notebook = kwargs.pop('notebook')
        super().__init__(*args, **kwargs)
        self.fields['notification_source'].label = 'Select a notification source for this task'
        self.fields['notification_source'].queryset = self.creator.notification_sources
        self.fields['accessible_datasets'].label = 'Select the datasets this task will make use of'
        self.fields['accessible_datasets'].queryset = self.creator.datasets
        self.fields['timeout'].help_text = 'leave empty, for no time limit'
        self.fields['secret_variables'].label = 'Add secret variable to task execution'
        self.fields['secret_variables'].queryset = Secret.objects.filter(creator=self.creator)
        self.fields['docker_image'].initial = "python:3.8-slim-buster"
        setattr(self.fields['notification_source'], 'create_link', reverse('notifications:create'))

    class Meta:
        model = PythonTask
        fields = ['name', 'timeout', 'secret_variables', 'accessible_datasets', 'notification_source',
                  'alert_on_failure', 'docker_image']

    def save(self, commit=True):
        task = super().save(commit=False)
        task.creator = self.creator
        task.task_type = Task.TaskTypeChoices.PYTHON
        if commit:
            task.python_file.save(f"exported_{self.notebook.id}", ContentFile(get_notebook_code(self.notebook)))
            task.save()
            self.save_m2m()
        return task

data-platform-master/notebooks/views.py
import os
import json
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ValidationError
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin, AccessMixin
from django.contrib import messages
from django.urls import reverse, reverse_lazy
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect, JsonResponse

from datasets.views import has_permission
from workflows.models import PythonTask
from notebooks.services.datasets import get_accessible_datasets
from notebooks.services.notebook import get_notebook_session_service
from notebooks.models import Cell
from notebooks.models import Notebook
from notebooks.models import CODE_SNIPPETS_DIR
from notebooks.forms import ExportNotebookForm, NotebookForm


class NotebookCreatorOnlyMixin(AccessMixin):
    def dispatch(self, request, *args, **kwargs):
        notebook = Notebook.objects.get(pk=kwargs["pk"])
        if notebook.creator.id != request.user.id:
            return self.handle_no_permission()
        return super().dispatch(request, *args, **kwargs)


class NotebooksListView(LoginRequiredMixin, generic.ListView):
    model = Notebook
    ITEMS_PER_PAGE = 10
    paginate_by = ITEMS_PER_PAGE

    def get_queryset(self):
        return Notebook.objects.filter(creator=self.request.user)


class NotebookDetailView(LoginRequiredMixin, generic.DetailView):
    model = Notebook

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["accessible_datasets"] = get_accessible_datasets(context["object"])
        return context


class NotebookDeleteView(LoginRequiredMixin, NotebookCreatorOnlyMixin, generic.DeleteView):
    model = Notebook
    success_url = reverse_lazy('notebooks:index')


class NotebookCreateView(LoginRequiredMixin, generic.CreateView):
    model = Notebook
    form_class = NotebookForm
    template_name = 'notebooks/notebook_create.html'

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        notebook = form.save()
        return HttpResponseRedirect(reverse('notebooks:detail', args=(notebook.id,)))


class ExportNotebook(LoginRequiredMixin, NotebookCreatorOnlyMixin, generic.CreateView):
    model = PythonTask
    form_class = ExportNotebookForm
    template_name = 'notebooks/export.html'

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        kwargs['notebook'] = get_object_or_404(Notebook, pk=self.kwargs['pk'])
        return kwargs

    def form_valid(self, form):
        task = form.save()
        messages.success(self.request, 'Your task has been created :)')
        return HttpResponseRedirect(reverse('workflows:detail_task', args=(task.id,)))


def snippets_list_view(request):
    _, _, filenames = next(os.walk(CODE_SNIPPETS_DIR))
    values = [
        {
            "name": os.path.splitext(name)[0].replace("_", " ").capitalize(),
            "value": os.path.splitext(name)[0]
        }
        for name in filenames
    ]
    return JsonResponse({"success": True, "results": values})


def snippet_detail_view(request, name):
    with open(f"{CODE_SNIPPETS_DIR}/{name}.py", "r", encoding="utf8") as file:
        return JsonResponse({"snippet": file.read()})


def restart_kernel_view(request, pk):
    session_service = get_notebook_session_service(pk)
    session_service.restart()
    return JsonResponse({})


# pylint: disable=unused-argument
def has_notebook_owner_perm(request, notebook_pk, cell_pk=0):
    notebook = get_object_or_404(Notebook, pk=notebook_pk)
    return notebook.creator.id == request.user.id


def serialize_cell(cell):
    return {"id": cell.id,
            "code": cell.code,
            "cell_status": cell.get_cell_status_display()}


def get_code_from_request(request):
    data = json.loads(request.body)
    code = data.get('code', None)
    if not code:
        code = ""
    return code


@login_required
@has_permission(has_notebook_owner_perm)
def cell_create_view(request, notebook_pk):
    code = get_code_from_request(request)
    notebook = Notebook.objects.filter(pk=notebook_pk).first()
    if not notebook:
        raise ValidationError("notebook is not valid")
    cell = Cell.objects.create(notebook=notebook, code=code)
    return JsonResponse(serialize_cell(cell))


@login_required
@has_permission(has_notebook_owner_perm)
def cell_update_view(request, notebook_pk, cell_pk):
    # pylint: disable=unused-argument
    cell = get_object_or_404(Cell, pk=cell_pk)
    code = get_code_from_request(request)

    cell.code = code
    cell.save()

    return JsonResponse(serialize_cell(cell))


@login_required
@has_permission(has_notebook_owner_perm)
def cell_delete_view(request, notebook_pk, cell_pk):
    # pylint: disable=unused-argument
    cell = get_object_or_404(Cell, pk=cell_pk)
    cell.delete()

    return JsonResponse({})

data-platform-master/notebooks/templates/notebooks/cell_item.html
<div class="cell-item">
    <div class="cell">
        <div class="cell-run" id="cell_run_{{ id }}" onclick="runCell({{ id }})">
            <i class="play icon"></i>
        </div>
        <div class="cell-code" onfocusout="saveCell({{ id }})">
            <div class="editor" id="cell_code_{{ id }}">{{ code }}</div>
        </div>
    </div>
    <div class="cell-toolbar">
        <div class="cell-buttons">
        <span data-tooltip="Delete cell" data-position="right center" onclick="deleteCell({{ id }})">
            <i class="ui trash alternate outline link icon"></i>
        </span>
        <span data-tooltip="Save" data-position="right center" onclick="saveCell({{ id }})">
            <i class="save outline link icon"></i>
        </span>
        </div>
        <div class="filler"></div>
        <div class="cell-status" id="cell_stat_{{ id }}">
            <i class=""></i>
        </div>
    </div>

</div>

data-platform-master/notebooks/templates/notebooks/cell_result.html
<div class="cell">
    <div class="cell-run"></div>
    <div class="cell-code">
        <div class="cell-res" id="cell_res_{{ id }}">print('hi')</div>
    </div>
</div>

data-platform-master/notebooks/templates/notebooks/export.html
{% extends 'data_platform/basic.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'users/styles/basic_form.css' %}">
{% endblock %}

{% block title %}Export Notebook{% endblock %}

{% block body %}


<div class="ui center aligned page grid segment">
    <form method="post" class="ui form">
        {% csrf_token %}
        {% include 'registration/basic_form.html' with form=form title='Export notebook as task' submit_value='Export'%}
    </form>
</div>


{% endblock %}

data-platform-master/notebooks/templates/notebooks/notebook_confirm_delete.html
{% extends 'data_platform/basic.html' %}
{% load static %}

{% block head %}{% endblock %}

{% block title %}Delete Notebook{% endblock %}

{% block body %}


<div class="ui center aligned page grid segment">
    <div class="delete_form_container">
        <h4>Are you sure you want to delete "{{ object.name }}"?</h4>
        <form method="post" class="ui form">
            {% csrf_token %}
            <br>
            <input type="submit" value="Yes, delete it" class="negative ui button">
            <a href="{% url 'notebooks:detail' view.object.id %}" class="ui button">Cancel</a>
        </form>
    </div>
</div>


{% endblock %}

data-platform-master/notebooks/templates/notebooks/notebook_create.html
{% extends 'data_platform/basic.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'users/styles/basic_form.css' %}">
{% endblock %}

{% block title %}Create Notebook{% endblock %}

{% block body %}


<div class="ui center aligned page grid segment">
    <form method="post" class="ui form">
        {% csrf_token %}
        {% include 'registration/basic_form.html' with form=form title='Create Notebook' submit_value='Create'%}
    </form>
</div>


{% endblock %}

data-platform-master/notebooks/templates/notebooks/notebook_detail.html
{% extends 'data_platform/basic.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{%static 'notebooks/styles/detail.css' %}">
<link rel="stylesheet" type="text/css" href="{%static 'data_platform/styles/toast.css' %}">
<script src="{%static 'data_platform/scripts/toast.js' %}"></script>
<script>
const notebookId = {{ object.id }}
const CSRFToken = `{{ csrf_token }}`
const cellItemHtmlString = `{% include 'notebooks/cell_item.html' with id="{id_placeholder}" code="" %}`
const cellResultHtmlString = `{% include 'notebooks/cell_result.html' with id="{id_placeholder}" %}`

</script>
<script src="{% static 'notebooks/scripts/detail.js' %}"></script>
<link rel="stylesheet" href="{% static 'notebooks/styles/codemirror.css' %}">
<script src="{% static 'notebooks/scripts/codemirror.js' %}"></script>
<script src="{% static 'notebooks/scripts/python.js' %}"></script>
{% endblock %}

{% block title %}Notebook{% endblock %}


{% block full_width_body %}

<div class="ui active dimmer" id="page-loading">
    <div class="ui loader"></div>
</div>


<div id="split-pane">
    <div id="side-pane">
        <div class="ui form">
            <h4>Code snippets:</h4>
            <div class="fields">
                <div class="field">
                    <div class="ui selection dropdown">
                        <div class="default text">Select code snippet...</div>
                        <i class="dropdown icon"></i>
                    </div>
                </div>
                <button class="ui button" onclick="addSnippet()">Add</button>
            </div>
        </div>

        {% if accessible_datasets %}
        <br><hr><br>
        <div class="ui form">
            <h4>Accessible Datasets:</h4>
                <div class="ui divided selection list">
                {% for dataset_name,dataset_mount_path in accessible_datasets.items %}
                    <a class="item">
                        <div class="ui horizontal label">{{dataset_name}}</div>
                        <input type="text" class="copyInput" value="{{dataset_mount_path}}">
                    </a>
                {% endfor %}
                </div>
        </div>
        {% endif %}
    </div>


    <div id="main-pane">
        <div class="toolbar">
            <h1>{{ object.name | title }}</h1>

            <div class="filler"></div>

            <button class="ui icon button" data-tooltip="Add new cell" onclick="addCell('')">
                <i class="plus icon"></i>
            </button>
            <button class="ui icon button" data-tooltip="Factory reset" onclick="restartSession()">
                <i class="sync alternate icon" id="restart-session-icon" ></i>
            </button>
            <a class="ui icon button" data-tooltip="Export notebook as task" href="{% url 'notebooks:export' object.id %}">
                <i class="share square icon"></i>
            </a>
            <a class="ui icon negative button" data-tooltip="Delete notebook"
               href="{% url 'notebooks:delete' object.id %}">
                <i class="trash alternate icon"></i>
            </a>
        </div>

        <div class="cell-list">
            {% for cell in object.cells.all %}
            {% include 'notebooks/cell_item.html' with id=cell.id code=cell.code %}
            {% endfor %}
        </div>
    </div>
</div>

<div id="toast"></div>


{% endblock %}

data-platform-master/notebooks/templates/notebooks/notebook_list.html
{% extends 'data_platform/basic.html' %}
{% load static %}

{% block head %}{% endblock %}

{% block title %}Notebooks{% endblock %}

{% block body %}


{% if  object_list  %}

<h1>Notebooks</h1>
<br>

<div class="ui relaxed divided list">
    {% for notebook in object_list reversed %}
    <div class="item">
        <i class="large code middle aligned icon"></i>
        <div class="content">
            <a class="header" href="{% url 'notebooks:detail' notebook.id %}">{{ notebook.name }}</a>
        </div>
    </div>
    {% endfor %}
</div>

<br>

{% include 'data_platform/pagination.html' %}

{% else %}
<h2>No available notebooks.</h2>
{% endif %}


<a href="{% url 'notebooks:create' %}">Create a new notebook</a>


{% endblock %}