data-platform-master/data_platform/urls.py
from django.contrib import admin
from django.urls import path, include
from users.views import dashboard

urlpatterns = [
    path('', dashboard, name='dashboard'),
    path('workflows/', include('workflows.urls')),
    path('admin/', admin.site.urls),

    path('users/', include('users.urls')),

    path('datasets/', include('datasets.urls')),
    path('notifications/', include('notifications.urls')),
    path('notebooks/', include('notebooks.urls')),
]

data-platform-master/datasets/urls.py
from django.urls import path

from . import views

app_name = "datasets"

datasets_urls = [
    path("", views.DatasetListView.as_view(visibility='private'), name="index"),
    path("public", views.DatasetListView.as_view(visibility='public'), name="public"),
    path("<int:pk>/", views.dataset_detail_view, name="detail"),
    path("<int:pk>/download/", views.dataset_download_view, name="download"),
    path("upload/", views.DatasetCreateView.as_view(), name="upload"),
    path("<int:pk>/edit/", views.DatasetUpdateView.as_view(), name="edit"),
    path("<int:pk>/delete/", views.DatasetDeleteView.as_view(), name="delete"),
]

datasource_urls = [
    path("datasources/", views.DataSourceListView.as_view(), name="list_datasource"),
    path("datasources/create", views.DataSourceCreateView.as_view(), name="create_datasource"),
    path("datasources/<int:pk>/", views.datasource_detail_view, name="detail_datasource"),
    path("datasources/<int:pk>/delete", views.DataSourceDeleteView.as_view(), name="delete_datasource"),
]

urlpatterns = [
    *datasets_urls,
    *datasource_urls,
]

data-platform-master/users/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
    path('logout/', auth_views.LogoutView.as_view(template_name='registration/logout.html'), name='logout'),
    path('', include('django.contrib.auth.urls')),
    path('signup/', views.Signup.as_view(), name='signup'),
]

data-platform-master/workflows/urls.py
from django.urls import path
from . import views

app_name = 'workflows'

workflows_urls = [
    path('', views.WorkflowListView.as_view(), name='list_workflow'),
    path('create/', views.WorkflowCreateView.as_view(), name='create_workflow'),
    path('<int:pk>/', views.WorkflowDetailView.as_view(), name='detail_workflow'),
    path('<int:pk>/dependencies/', views.TaskDependencyCreateView.as_view(), name='manage_dependencies'),
    path('<int:pk>/delete/', views.WorkflowDeleteView.as_view(), name='delete_workflow'),
    path('<int:pk>/run/', views.WorkflowRunView.as_view(), name='run_workflow'),
    path('<int:pk>/schedule/', views.WorkflowScheduleRedirectView.as_view(), name='schedule_workflow'),
    path('<int:pk>/schedule/paused/', views.workflow_schedule_paused_view, name='schedule_paused'),
]

tasks_urls = [
    path('tasks/', views.TaskListView.as_view(), name='list_task'),
    path('tasks/create/', views.create_task_view, name='create_task'),
    path('tasks/create/forms/<str:task_type>', views.get_typed_task_form, name='typed_form'),
    path('tasks/<int:pk>/', views.TaskDetailView.as_view(), name='detail_task'),
    path('tasks/<int:pk>/delete/', views.TaskDeleteView.as_view(), name='delete_task'),
    path('tasks/<int:pk>/executions/<int:exec_pk>/mark/', views.task.stop_task_execution_view,
         name='stop_task_execution'),
    path('tasks/<int:pk>/run/', views.task.run_task_view, name='run'),
]

secret_urls = [
    path('secrets/', views.SecretListView.as_view(), name='list_secret'),
    path('secrets/create/', views.SecretCreateView.as_view(), name='create_secret'),
    path('secrets/<int:pk>/', views.SecretDetailView.as_view(), name='detail_secret'),
    path('secrets/<int:pk>/delete/', views.SecretDeleteView.as_view(), name='delete_secret'),
]

urlpatterns = [
    path('tasks/executions/<int:pk>/', views.task.TaskExecutionDetailView.as_view(), name='detail_task_execution'),
    *tasks_urls,
    *secret_urls,
    *workflows_urls,
]

data-platform-master/workflows/models/docker.py
from django.db import models
from workflows.models.task import Task


class DockerTask(Task):
    docker_image = models.CharField(max_length=255)

data-platform-master/workflows/models/python.py
from django.core import validators
from django.db import models
from .task import Task


def user_python_file_directory_path(instance, filename):
    # file will be uploaded to MEDIAROOT/user<id>/datasets/<filename>
    return f"workflows/python_files/{instance.creator.username}/{filename}"


class PythonTask(Task):
    python_file = models.FileField(
        upload_to=user_python_file_directory_path,
        validators=[
            validators.FileExtensionValidator(allowed_extensions=["py"]),
        ])

    docker_image = models.CharField(
        max_length=255,
        default="python:3.8-alpine"
    )

data-platform-master/workflows/models/secret.py
from django.db import models
from django.contrib.auth.models import User



class Secret(models.Model):
    name = models.CharField(max_length=255)
    value = models.TextField()
    creator = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.name)

data-platform-master/workflows/models/task.py
from django.utils.translation import gettext_lazy as _
from django.db import models
from django.contrib.auth.models import User
from workflows.models.secret import Secret
from datasets.models import Dataset
from notifications.models import NotificationSource


def task_execution_log_file_directory_path(instance, filename):
    # pylint: disable=unused-argument
    return f"workflows/task_execution_logs/{filename}"


class Task(models.Model):
    class TaskTypeChoices(models.TextChoices):
        DOCKER = "DC", _("Docker")
        PYTHON = "PY", _("Python")

    DEFAULT_TYPE = TaskTypeChoices.DOCKER

    name = models.CharField(max_length=255)
    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    secret_variables = models.ManyToManyField(Secret, blank=True)
    accessible_datasets = models.ManyToManyField(Dataset, blank=True)

    notification_source = models.ForeignKey(NotificationSource, on_delete=models.SET_NULL, null=True, blank=True)
    alert_on_failure = models.BooleanField(default=False)

    timeout = models.DurationField(null=True, blank=True)
    task_type = models.CharField(max_length=2, choices=TaskTypeChoices.choices, default=DEFAULT_TYPE)

    def __str__(self):
        return str(self.name)


class TaskExecution(models.Model):
    class StatusChoices(models.TextChoices):
        RUNNING = "R", _("Running")
        SUCCESS = "S", _("Success")
        FAILED = "F", _("Failed")
        PENDING = "P", _("Pending")

    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    status = models.CharField(max_length=1, choices=StatusChoices.choices, default=StatusChoices.PENDING, db_index=True)
    celery_task_id = models.CharField(max_length=50, null=True, blank=True)
    log = models.FileField(upload_to=task_execution_log_file_directory_path, null=True, blank=True)
    run_time = models.IntegerField(blank=True, null=True)  # in seconds
    extracted_datasets = models.ManyToManyField(Dataset, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

data-platform-master/workflows/models/workflow.py
from datetime import timedelta
from django.db import models
from django.contrib import auth

from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

DEFAULT_MAX_ACTIVE_EXECUTIONS = 10


class Workflow(models.Model):
    name = models.CharField(max_length=255)
    creator = models.ForeignKey(auth.get_user_model(), on_delete=models.CASCADE)
    max_active_executions_count = models.IntegerField(default=DEFAULT_MAX_ACTIVE_EXECUTIONS, blank=True)

    def __str__(self):
        return str(self.name)

    def exceeds_active_execution_limit(self):
        active_executions_count = self.get_active_executions_count()
        return active_executions_count >= self.max_active_executions_count

    def get_active_executions_count(self):
        return self.workflowexecution_set.filter(status=WorkflowExecution.StatusChoices.RUNNING).count()


class WorkflowExecution(models.Model):
    class StatusChoices(models.TextChoices):
        """Different statuses of workflow execution, including:
         PENDING: the status in which the workflow execution is waiting for its first task dependency to run
         RUNNING: the status in which at least one task dependency of the workflow has started running
         SUCCESS: the status in which all the task dependencies of the workflow have been successfully run
         FAILED: the status in which at least one task dependency has failed
         """
        RUNNING = "R", _("Running")
        SUCCESS = "S", _("Success")
        FAILED = "F", _("Failed")
        PENDING = "P", _("Pending")

    workflow = models.ForeignKey(Workflow, on_delete=models.CASCADE)
    status = models.CharField(max_length=1, choices=StatusChoices.choices, default=StatusChoices.PENDING, db_index=True)
    created_at = models.DateTimeField(auto_now_add=True)


def validate_schedule_interval(value):
    if value < timedelta(minutes=1):
        raise ValidationError(_('Schedule interval should be more than 1 minute.'))


class WorkflowSchedule(models.Model):
    workflow = models.OneToOneField(Workflow, on_delete=models.CASCADE, related_name='schedule')

    start_time = models.DateTimeField()
    schedule_interval = models.DurationField(validators=[validate_schedule_interval])

    next_run_time = models.DateTimeField(blank=True, null=True)

    paused = models.BooleanField(default=False, db_index=True)

data-platform-master/workflows/views/secret.py
from django.contrib import messages
from django.urls import reverse
from django.views.generic import CreateView, DeleteView, DetailView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin, AccessMixin
from django.http import HttpResponseRedirect
from workflows.models import Secret
from workflows.forms import SecretForm


class SecretCreatorOnlyMixin(AccessMixin):
    """Verify that the current user is the creator."""

    def dispatch(self, request, *args, **kwargs):
        secret_id = kwargs.get("pk", None)
        secret = Secret.objects.get(id=secret_id)
        if secret.creator.id != request.user.id:
            return self.handle_no_permission()
        return super().dispatch(request, *args, **kwargs)


class SecretListView(LoginRequiredMixin, ListView):
    ITEMS_PER_PAGE = 10
    paginate_by = ITEMS_PER_PAGE
    model = Secret
    template_name = 'secret/list_secret.html'
    context_object_name = 'secrets'

    def get_queryset(self):
        return Secret.objects.filter(creator=self.request.user)


class SecretDetailView(LoginRequiredMixin, SecretCreatorOnlyMixin, DetailView):
    model = Secret
    template_name = 'secret/detail_secret.html'
    context_object_name = 'secret'


class SecretCreateView(LoginRequiredMixin, CreateView):
    model = Secret
    form_class = SecretForm
    template_name = "secret/create_secret.html"

    def form_valid(self, form):
        secret = form.save(commit=False)
        secret.creator = self.request.user
        secret.save()
        messages.success(self.request, 'Your Secret has been created :)')
        success_url = reverse("workflows:detail_secret", args=(secret.pk,))
        return HttpResponseRedirect(success_url)


class SecretDeleteView(LoginRequiredMixin, SecretCreatorOnlyMixin, DeleteView):
    model = Secret

    def get_success_url(self):
        return reverse("workflows:list_secret")

data-platform-master/workflows/views/task.py
from django.http import HttpResponseRedirect

from django.views.generic import DeleteView, DetailView, ListView
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin, AccessMixin
from django.shortcuts import render, get_object_or_404
from django.template.loader import render_to_string
from django.http import JsonResponse, HttpResponse
from django.contrib.auth.decorators import login_required
from django.template.defaulttags import register

from workflows.models import Task, TaskExecution
from workflows.forms import TaskForm, TASK_TYPED_FORM_REGISTRY
from workflows.views.workflow import STATUS_CONTEXT_DICT
from workflows.services.docker import task_status_color, get_special_display_fields, get_task_type, DockerTaskService, \
    MarkTaskExecutionStatusOptions, read_task_execution_log_file
from workflows.services.runner import get_service_runner

from workflows.services.run_task import run_task


class CreatorOnlyMixin(AccessMixin):
    """Verify that the current user is the creator."""

    def dispatch(self, request, *args, **kwargs):
        task_id = kwargs.get("pk", None)
        task = Task.objects.get(id=task_id)
        if task.creator.id != request.user.id:
            return self.handle_no_permission()
        return super().dispatch(request, *args, **kwargs)


class TaskExecutionCreatorOnlyMixin(AccessMixin):
    """Verify that the current user is the creator."""

    def dispatch(self, request, *args, **kwargs):
        task_execution_id = kwargs.get("pk", None)
        task_execution = TaskExecution.objects.get(id=task_execution_id)
        if task_execution.task.creator.id != request.user.id:
            return self.handle_no_permission()
        return super().dispatch(request, *args, **kwargs)


class TaskDetailView(LoginRequiredMixin, CreatorOnlyMixin, DetailView):
    model = Task
    template_name = 'detail_task.html'
    context_object_name = 'task'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        task = context["task"]
        task.get_task_type_display = get_task_type(task)

        task_executions = TaskExecution.objects.filter(task=task)
        task.executions = task_executions
        for task_execution in task_executions:
            task_execution.status_color = task_status_color(task_execution.get_status_display())

        context["special_display_fields"] = get_special_display_fields(task)
        context["accessible_datasets"] = DockerTaskService.get_accessible_datasets_mount_info(task)
        context["mark_options"] = [
            {
                "value": MarkTaskExecutionStatusOptions.FAILED.value,
                "text": "failed",
                "color": "red",
            },
            {
                "value": MarkTaskExecutionStatusOptions.SUCCESS.value,
                "text": "success",
                "color": "green",
            }
        ]

        return context


@login_required
def create_task_view(request):
    if request.method == 'POST':
        form = TaskForm(request.POST, request.FILES, user=request.user)
        typed_form = TASK_TYPED_FORM_REGISTRY[request.POST['task_type']](request.POST, request.FILES)
        if form.is_valid():
            task = form.save()
            return HttpResponseRedirect(reverse('workflows:detail_task', args=(task.id,)))
    else:
        form = TaskForm(user=request.user)
        typed_form = TASK_TYPED_FORM_REGISTRY[Task.DEFAULT_TYPE]()
    return HttpResponse(render(request, 'create_task.html', context={'form': form, 'typed_form': typed_form}))


def get_typed_task_form(request, task_type):
    context = {'form': TASK_TYPED_FORM_REGISTRY[task_type]()}
    return JsonResponse({'form': render_to_string('registration/base_inline_form.html', context=context)})


class TaskDeleteView(LoginRequiredMixin, CreatorOnlyMixin, DeleteView):
    model = Task

    def get_success_url(self):
        return reverse("workflows:list_task")


class TaskListView(LoginRequiredMixin, ListView):
    ITEMS_PER_PAGE = 10
    paginate_by = ITEMS_PER_PAGE
    model = Task
    template_name = 'list_task.html'
    context_object_name = 'tasks'

    def get_queryset(self):
        tasks = Task.objects.filter(creator=self.request.user)
        for task in tasks:
            task.get_task_type_display = get_task_type(task)

        return tasks

    @register.filter
    def get_value(self, key):
        return self.get(key)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['status'] = STATUS_CONTEXT_DICT
        return context

def run_task_view(request, pk):
    task = get_object_or_404(Task, pk=pk)
    run_task(task)
    success_url = reverse("workflows:detail_task", args=(task.pk,))
    return HttpResponseRedirect(success_url)


def stop_task_execution_view(request, pk, exec_pk):
    task = get_object_or_404(Task, pk=pk)
    task_runner = get_service_runner(task)
    task_runner.stop_task_execution(
        task_execution_id=exec_pk,
        mark_task_execution_status_as=MarkTaskExecutionStatusOptions(int(request.POST["mark_option"])),
    )

    success_url = reverse("workflows:detail_task", args=(task.pk,))
    return HttpResponseRedirect(success_url)


class TaskExecutionDetailView(LoginRequiredMixin, TaskExecutionCreatorOnlyMixin, DetailView):
    model = TaskExecution
    template_name = 'detail_task_execution.html'
    context_object_name = 'task_execution'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        task_execution = context["task_execution"]
        context["extracted_datasets"] = task_execution.extracted_datasets.all()
        try:
            context["task_execution_have_log"] = True
            context["task_execution_log"] = read_task_execution_log_file(task_execution)
        except FileNotFoundError:
            context["task_execution_have_log"] = False
        return context

data-platform-master/workflows/templates/create_task.html
{% extends 'data_platform/basic.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'users/styles/basic_form.css' %}">
<style>li {
    font-size: 17px;
    list-style: none;
    margin: 15px auto;
}

</style>
<link rel="stylesheet" type="text/css" href="{%static 'data_platform/styles/toast.css' %}">
<script src="{%static 'data_platform/scripts/toast.js' %}"></script>
<script>
const url = `{{ request.scheme }}://{{ request.META.HTTP_HOST }}{{ request.path }}`
const typeSelectId = `id_task_type`

</script>
<script src="{% static 'data_platform/scripts/typed_form.js' %}"></script>
{% endblock %}

{% block title %}Create Task{% endblock %}

{% block body %}


<div class="ui center aligned page grid segment">
    <form enctype="multipart/form-data" action="{% url 'workflows:create_task' %}" method="post" class="ui form">
        {% csrf_token %}
        <div class="ui grid">
            <div class="left floated left aligned sixteen wide column">
                {% include 'registration/basic_form.html' with form=form title='Create a task'%}
            </div>
            <div class="left floated left aligned sixteen wide column" id="typed_form">
                {% include 'registration/base_inline_form.html' with form=typed_form %}
            </div>
            <input type="submit" value="Create task" class="ui button" style="margin-top: 20px;">
        </div>
    </form>
</div>


<div id="toast"></div>


{% endblock %}

data-platform-master/workflows/templates/detail_task.html
{% extends 'data_platform/basic.html' %}
{% load static %}

{% block head %}
<style>li {
        font-size: 17px;
        list-style: none;
        margin: 15px auto;
    }

</style>
<link rel="stylesheet" type="text/css" href="{% static 'data_platform/styles/basic_info.css' %}">
{% endblock %}

{% block title %}Task Details{% endblock %}

{% block body %}


<div class="ui segment">
    <h4><a href="{% url 'workflows:list_task' %}">Back to list</a></h4>
    <ul>
        {# Fix this return url, go somewhere better instead of the task list#}
        <div class="separator medium"></div>
        <h1>{{ task.name }}</h1>
        <div class="separator medium"></div>
        <div class="ui grid info-grid">
            {% for key,value in special_display_fields.items %}
            <div class="left floated left aligned four wide column key">
                {{ key }}:
            </div>
            <div class="left floated left aligned twelve wide column value">
                {{ value }}
            </div>
            {% endfor %}
            <div class="left floated left aligned four wide column key">
                Type:
            </div>
            <div class="left floated left aligned twelve wide column value">
                {{ task.get_task_type_display }}
            </div>
            {% if task.secret_variables.all %}
            <div class="left floated left aligned four wide column key">
                Accessible secret variables:
            </div>
            <div class="left floated left aligned twelve wide column value">
                <ul>
                    {% for secret_variable in task.secret_variables.all %}
                    <li>
                        <i class="right triangle icon grey"></i>
                        {{ secret_variable.name }}
                    <li>
                        {% endfor %}
                </ul>
            </div>
            {% endif %}
            <div class="left floated left aligned four wide column key">
                Creator:
            </div>
            <div class="left floated left aligned twelve wide column value">
                {% if task.creator.get_full_name %}
                {{ task.creator.get_full_name }}
                {% else %}
                {{ task.creator.username }}
                {% endif %}
            </div>
            {% if accessible_datasets %}
            <div class="left floated left aligned four wide column key">
                Accessible datasets:
            </div>
            <div class="left floated left aligned twelve wide column value">
                <ul>
                    {% for dataset_path in accessible_datasets %}
                    <li>
                        <i class="right triangle icon grey"></i>
                        {{ dataset_path }}
                    </li>
                    {% endfor %}
                </ul>
            </div>
            {% endif %}
        </div>

        {% if task.executions %}
        <div class="separator large"></div>
        <h3>Executions:</h3>

        <div class="ui relaxed divided list">
            {% for execution in task.executions reversed %}
            <div class="item" style="display: flex; align-items: center;">
                <i class="large cogs middle aligned icon"></i>
                <div class="content">
                    <a class="header" href="{% url 'workflows:detail_task_execution' execution.id %}">
                        <span style="color: {{ execution.status_color }}; font-size: medium; margin-left: 8px;">{{ execution.get_status_display }}</span></a>
                </div>
                {% for mark_option in mark_options %}
                <form method="post"
                      style="margin: 10px;"
                      action="{% url 'workflows:stop_task_execution' pk=task.id exec_pk=execution.id %}">
                    {% csrf_token %}
                    <input type="hidden" name="mark_option" value="{{ mark_option.value }}"/>
                    <input type="submit" value="Mark {{ mark_option.text }}"
                           class="ui right floated {{ mark_option.color }} button">
                </form>
                {% endfor %}
            </div>
            {% endfor %}
        </div>
        {% else %}
        <div class="separator medium"></div>
        {% endif %}
        <div style="display: flex;">
            <form method="post" style="margin: 10px;" action="delete/">{% csrf_token %}
                <input type="submit" value="Delete" class="negative ui button">
            </form>
            <span style="margin: 10px 2px;">
                <a class="positive ui icon button"
                   data-tooltip="Include task in a workflow to run!">
                    Run Task
                </a>
            </span>
        </div>
    </ul>
</div>

{% endblock %}

data-platform-master/workflows/templates/detail_workflow.html
{% extends 'data_platform/basic.html' %}
{% load static %}

{% block head %}
<style>
        li {
            font-size: 17px;
            list-style: none;
            margin: 15px auto;
        }

</style>
{% endblock %}

{% block title %}Workflow Details{% endblock %}

{% block body %}

<div class="ui segment">
    <h4><a href="{% url 'workflows:list_workflow' %}">Back to list</a></h4>
    <ul>
        <li><h1>{{ workflow.name }}</h1></li>
        <div class="ui pointing secondary menu">
            <a class="item active" data-tab="DAG">Task Dependencies DAG</a>
            <a class="item" data-tab="DURATION">Tasks Duration</a>
            <a class="item" data-tab="EXECUTIONS">Executions History</a>
        </div>
        <div class="ui tab active" data-tab="DAG">
            {% include 'workflows/DAG.html' %}
        </div>
        <div class="ui tab" data-tab="DURATION">
            {% include 'workflows/task_duration.html' %}
        </div>
        <div class="ui tab" data-tab="EXECUTIONS">
            {% include 'workflows/workflow_executions_history.html' %}
        </div>
    </ul>
</div>

<script>
    $('.ui.pointing.menu .item').tab();


</script>
{% endblock %}

data-platform-master/workflows/templates/list_task.html
{% extends 'data_platform/basic.html' %}
{% load static %}

{% block head %}
<style>li {
    font-size: 17px;
    list-style: none;
    margin: 15px auto;
}

</style>
{% endblock %}

{% block title %}Tasks{% endblock %}

{% block body %}
{% if  tasks %}
<h1>Tasks<br></h1>
<br>

<table class="ui very basic table">
    <thead>
    <tr>
        <th>Name</th>
        <th>Type</th>
        <th>Last Execution</th>
        <th>Actions</th>
    </tr>
    </thead>
    <tbody>
    {% for task in tasks reversed %}
    <tr>
        <td>
            <i class="check left aligned icon"></i>
            <a class="header" href="{{ task.pk }}/">{{ task.name }}</a>
        </td>
        <td>{{ task.get_task_type_display }}</td>
        {% if task.taskexecution_set.last %}
        <td>
            {% with task_execution_status=status|get_value:task.taskexecution_set.last.status %}
            <a class="header" href="executions/{{ task.taskexecution_set.last }}/">
                <div class="column"
                    style=" margin: 5px; border-radius: 50%; width: 20px; height: 20px;
                            background-color: {{ task_execution_status.color }}"
                    title="status: {{ task_execution_status.text }}">
                </div>
            </a>
            {% endwith %}
        {% else %}
        <td>N/A</td>
        {% endif %}
        <td>
            <span style="margin: 10px 2px;">
                <a href="{% url 'workflows:delete_task' task.id %}" class="negative ui icon button"
                    data-tooltip="Delete Task">
                    <i class="trash middle aligned icon"></i>
                </a>
            </span>
        </td>
    {% endfor %}
    </tbody>
</table>

<br>

{% include 'data_platform/pagination.html' %}

{% else %}
<h2>No tasks available.</h2>
{% endif %}

<br>

<a href="{% url 'workflows:create_task' %}">add new task</a>
<br>


{% endblock %}

data-platform-master/workflows/templates/list_workflow.html
{% extends 'data_platform/basic.html' %}
{% load static %}

{% block head %}
<style>li {
    font-size: 17px;
    list-style: none;
    margin: 15px auto;
}

</style>
<script>
    const CSRFToken = `{{ csrf_token }}`
</script>
<link rel="stylesheet" type="text/css" href="{%static 'data_platform/styles/toast.css' %}">
<script src="{% static 'data_platform/scripts/toast.js' %}"></script>
<script src="{% static 'workflows/scripts/workflow_list.js' %}"></script>
{% endblock %}

{% block title %}Workflows{% endblock %}

{% block body %}
{% if  workflows %}
<h1>Workflows<br></h1>
<br>

<table class="ui very basic table">
    <thead>
    <tr>
        <th>Name</th>
        <th>Creator</th>
        <th>Last run status</th>
        <th>Last run time</th>
        <th>Active runs</th>
        <th>Actions</th>
    </tr>
    </thead>
    <tbody>
    {% for workflow in workflows reversed %}
    <tr>
        <td>
            <i class="tasks large left aligned icon"></i>
            <a class="header" href="{{ workflow.pk }}/" style="font-weight: bold;">{{ workflow.name }}</a>
        </td>
        <td>{{ workflow.creator.username }}</td>
        {% if workflow.workflowexecution_set.last %}
        <td>
            {% with workflow_execution_status=status|get_value:workflow.workflowexecution_set.last.status %}
            <div class="column"
                 style=" margin: 5px; border-radius: 50%; width: 20px; height: 20px;
                        background-color: {{ workflow_execution_status.color }}"
                 title="status: {{ workflow_execution_status.text }}">
            </div>
            {% endwith %}
        </td>
        <td>{{ workflow.workflowexecution_set.last.created_at }}</td>
        {% else %}
        <td>N/A</td>
        <td>N/A</td>
        {% endif %}
        <td>{{ workflow.get_active_executions_count }}</td>
        <td style="display: flex;">
            <form method="post" style="margin: 10px 5px;" action="{% url 'workflows:run_workflow' workflow.id %}">
                {% csrf_token %}
                <button type="submit" class="positive ui icon button" data-tooltip="Run workflow">
                    <i class="play circle middle aligned icon"></i>
                </button>
            </form>
            <span style="margin: 10px 2px;">
                <a href="{% url 'workflows:delete_workflow' workflow.id %}" class="negative ui icon button"
                    data-tooltip="Delete workflow">
                    <i class="trash middle aligned icon"></i>
                </a>
            </span>
            <span style="margin: 10px 2px;">
                <a href="{% url 'workflows:schedule_workflow' workflow.id %}" class="ui icon button"
                    data-tooltip="Schedule workflow">
                    <i class="clock icon"></i>
                </a>
            </span>
            <span style="margin: 10px 2px;">
                <a href="{% url 'workflows:manage_dependencies' workflow.id %}" class="ui icon button"
                    data-tooltip="Manage task dependencies">
                    <i class="sitemap icon"></i>
                </a>
            </span>
            {% if workflow.schedule %}
            <form method="post" style="margin: 10px 2px; display: flex; justify-content: center; align-items: center;">
                {% csrf_token %}
                <span class="ui toggle checkbox" id="schedule_{{ workflow.id }}"
                    style="display: flex; font-size: smaller; color: grey;">
                    <input type="checkbox" name="pause" onchange="changePauseStatus(this, {{ workflow.id }})"
                            {% if not workflow.schedule.paused %}checked=""{% endif %}>{% if workflow.schedule.paused %}OFF{% else %}ON{% endif %}</span>
            </form>
            {% endif %}
        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>

<br>

{% include 'data_platform/pagination.html' %}

{% else %}
<h2>No workflows available.</h2>
{% endif %}

<br>
<a href="{% url 'workflows:create_workflow' %}">Add new workflow</a>
<br>

<div id="toast"></div>

{% endblock %}