data-platform-master/data_platform/urls.py
from django.contrib import admin
from django.urls import path, include
from users.views import dashboard

urlpatterns = [
    path('', dashboard, name='dashboard'),
    path('workflows/', include('workflows.urls')),
    path('admin/', admin.site.urls),

    path('users/', include('users.urls')),

    path('datasets/', include('datasets.urls')),
    path('notifications/', include('notifications.urls')),
    path('notebooks/', include('notebooks.urls')),
]

data-platform-master/datasets/urls.py
from django.urls import path

from . import views

app_name = "datasets"

datasets_urls = [
    path("", views.DatasetListView.as_view(visibility='private'), name="index"),
    path("public", views.DatasetListView.as_view(visibility='public'), name="public"),
    path("<int:pk>/", views.dataset_detail_view, name="detail"),
    path("<int:pk>/download/", views.dataset_download_view, name="download"),
    path("upload/", views.DatasetCreateView.as_view(), name="upload"),
    path("<int:pk>/edit/", views.DatasetUpdateView.as_view(), name="edit"),
    path("<int:pk>/delete/", views.DatasetDeleteView.as_view(), name="delete"),
]

datasource_urls = [
    path("datasources/", views.DataSourceListView.as_view(), name="list_datasource"),
    path("datasources/create", views.DataSourceCreateView.as_view(), name="create_datasource"),
    path("datasources/<int:pk>/", views.datasource_detail_view, name="detail_datasource"),
    path("datasources/<int:pk>/delete", views.DataSourceDeleteView.as_view(), name="delete_datasource"),
]

urlpatterns = [
    *datasets_urls,
    *datasource_urls,
]

data-platform-master/notebooks/urls.py
from django.urls import path
from django.urls import re_path

from . import consumers
from . import views

app_name = "notebooks"

urlpatterns = [
    # notebook crud
    path("", views.NotebooksListView.as_view(), name="index"),
    path("create/", views.NotebookCreateView.as_view(), name="create"),
    path("<int:pk>/", views.NotebookDetailView.as_view(), name="detail"),
    path("<int:pk>/delete/", views.NotebookDeleteView.as_view(), name="delete"),
    path("<int:pk>/export/", views.ExportNotebook.as_view(), name="export"),
    path("<int:pk>/restart_kernel/", views.restart_kernel_view, name="restart_kernel"),
    # cell api
    path("<int:notebook_pk>/cell/create/", views.cell_create_view, name="cell_create"),
    path("<int:notebook_pk>/cell/update/<int:cell_pk>/", views.cell_update_view, name="cell_update"),
    path("<int:notebook_pk>/cell/delete/<int:cell_pk>/", views.cell_delete_view, name="cell_delete"),
    # code snippets
    path("snippets/", views.snippets_list_view, name="snippets"),
    path("snippets/<str:name>/", views.snippet_detail_view, name="snippet_detail"),
]

websocket_urlpatterns = [
    re_path(r'ws/notebook/(?P<notebook_id>\d+)/$', consumers.NotebookConsumer.as_asgi()),
]

data-platform-master/users/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
    path('logout/', auth_views.LogoutView.as_view(template_name='registration/logout.html'), name='logout'),
    path('', include('django.contrib.auth.urls')),
    path('signup/', views.Signup.as_view(), name='signup'),
]

data-platform-master/workflows/urls.py
from django.urls import path
from . import views

app_name = 'workflows'

workflows_urls = [
    path('', views.WorkflowListView.as_view(), name='list_workflow'),
    path('create/', views.WorkflowCreateView.as_view(), name='create_workflow'),
    path('<int:pk>/', views.WorkflowDetailView.as_view(), name='detail_workflow'),
    path('<int:pk>/dependencies/', views.TaskDependencyCreateView.as_view(), name='manage_dependencies'),
    path('<int:pk>/delete/', views.WorkflowDeleteView.as_view(), name='delete_workflow'),
    path('<int:pk>/run/', views.WorkflowRunView.as_view(), name='run_workflow'),
    path('<int:pk>/schedule/', views.WorkflowScheduleRedirectView.as_view(), name='schedule_workflow'),
    path('<int:pk>/schedule/paused/', views.workflow_schedule_paused_view, name='schedule_paused'),
]

tasks_urls = [
    path('tasks/', views.TaskListView.as_view(), name='list_task'),
    path('tasks/create/', views.create_task_view, name='create_task'),
    path('tasks/create/forms/<str:task_type>', views.get_typed_task_form, name='typed_form'),
    path('tasks/<int:pk>/', views.TaskDetailView.as_view(), name='detail_task'),
    path('tasks/<int:pk>/delete/', views.TaskDeleteView.as_view(), name='delete_task'),
    path('tasks/<int:pk>/executions/<int:exec_pk>/mark/', views.task.stop_task_execution_view,
         name='stop_task_execution'),
    path('tasks/<int:pk>/run/', views.task.run_task_view, name='run'),
]

secret_urls = [
    path('secrets/', views.SecretListView.as_view(), name='list_secret'),
    path('secrets/create/', views.SecretCreateView.as_view(), name='create_secret'),
    path('secrets/<int:pk>/', views.SecretDetailView.as_view(), name='detail_secret'),
    path('secrets/<int:pk>/delete/', views.SecretDeleteView.as_view(), name='delete_secret'),
]

urlpatterns = [
    path('tasks/executions/<int:pk>/', views.task.TaskExecutionDetailView.as_view(), name='detail_task_execution'),
    *tasks_urls,
    *secret_urls,
    *workflows_urls,
]

data-platform-master/data_platform/templates/data_platform/basic.html
{% load static %}
<html lang="en">

<head>
    <script src="{% static 'data_platform/scripts/jquery.js' %}"></script>
    {% block head %}
    <!--style, link and other head tags go here-->
    {% endblock %}
    <style>
        body {
            font-family: Garamond, sans-serif;
            overflow-x: hidden;
            height: 100%;
            padding: 0;
            margin: 0;
        }

        html {
            height: 100%;
            padding: 0;
            margin: 0;
        }
    </style>
    <link rel="stylesheet" type="text/css" href="{% static 'data_platform/styles/basic.css' %}">
    <meta charset="utf-8">
    <meta name="author" content="SummerCamp_Bakend_Team3">
    <meta name="keywords" content="dataset, workflow, task, data">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link type="text/css" rel="stylesheet" href="{% static 'data_platform/styles/semantic.css' %}">
    <script src="{% static 'data_platform/scripts/semantic.js' %}"></script>
    <title>{% block title %}<!--page title goes here-->{% endblock %}</title>
</head>

<body>
{% include 'data_platform/nav_bar.html' %}
<div style="padding: 30px;" class="ui container">
    {% include "data_platform/messages.html" %}
    {% block body %}
    <!--body goes here-->
    {% endblock %}
</div>
<div style="margin: 0px 50px 0px 50px">
    {% block full_width_body %}
    <!--used for non-centralized body-->
    {% endblock %}
</div>
</body>

</html>

data-platform-master/data_platform/templates/data_platform/messages.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'data_platform/styles/messages.css' %}">

{% for message in messages %}
<div class="ui {{ message.tags }} message">
  <h1 class="message">{{ message }}</h1>
</div>
{% endfor %}

data-platform-master/data_platform/templates/data_platform/nav_bar.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'data_platform/styles/nav_bar.css' %}">

<div class="nav_bar_container">
    <a href="{% url 'dashboard' %}">
        <h1>Data
            <span style="color: rgb(16,84,113);">Platform</span>
        </h1>
    </a>
    <div class="filler"></div>
    <div class="nav_item_container">
        <nav id="navbar">
            <a href="{% url 'datasets:public' %}" class="menu-item">Explore datasets</a>
            {% if not request.user.is_authenticated %}
                <a href="{% url 'users:login' %}" class="menu-item">Login</a>
                <a href="{% url 'users:signup' %}" class="menu-item">Sign up</a>
            {% else %}
                <a href="{% url 'datasets:index' %}" class="menu-item">Datasets</a>
                <a href="{% url 'datasets:list_datasource' %}" class="menu-item">Data Sources</a>
                <a href="{% url 'workflows:list_workflow' %}" class="menu-item">Workflows</a>
                <a href="{% url 'workflows:list_task' %}" class="menu-item">Tasks</a>
                <a href="{% url 'workflows:list_secret' %}" class="menu-item">Secrets</a>
                <a href="{% url 'notebooks:index' %}" class="menu-item">Notebooks</a>
                <a href="{% url 'users:logout' %}" class="menu-item">Sign out</a>
                <span style="font-style: italic">
                    <i class="user circle outline icon"></i>
                    Signed in as: {{ request.user.username }}</span>
            {% endif %}
        </nav>
    </div>
</div>

data-platform-master/data_platform/templates/data_platform/pagination.html
{% load query_params %}

<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="{% append_param request 'page' 1 %}">&laquo; first</a>
            <a href="{% append_param request 'page' page_obj.previous_page_number %}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="{% append_param request 'page' page_obj.next_page_number %}">next</a>
            <a href="{% append_param request 'page' page_obj.paginator.num_pages %}">last &raquo;</a>
        {% endif %}
    </span>
</div>