data-platform-master/data_platform/urls.py
from django.contrib import admin
from django.urls import path, include
from users.views import dashboard

urlpatterns = [
    path('', dashboard, name='dashboard'),
    path('workflows/', include('workflows.urls')),
    path('admin/', admin.site.urls),

    path('users/', include('users.urls')),

    path('datasets/', include('datasets.urls')),
    path('notifications/', include('notifications.urls')),
    path('notebooks/', include('notebooks.urls')),
]

data-platform-master/datasets/urls.py
from django.urls import path

from . import views

app_name = "datasets"

datasets_urls = [
    path("", views.DatasetListView.as_view(visibility='private'), name="index"),
    path("public", views.DatasetListView.as_view(visibility='public'), name="public"),
    path("<int:pk>/", views.dataset_detail_view, name="detail"),
    path("<int:pk>/download/", views.dataset_download_view, name="download"),
    path("upload/", views.DatasetCreateView.as_view(), name="upload"),
    path("<int:pk>/edit/", views.DatasetUpdateView.as_view(), name="edit"),
    path("<int:pk>/delete/", views.DatasetDeleteView.as_view(), name="delete"),
]

datasource_urls = [
    path("datasources/", views.DataSourceListView.as_view(), name="list_datasource"),
    path("datasources/create", views.DataSourceCreateView.as_view(), name="create_datasource"),
    path("datasources/<int:pk>/", views.datasource_detail_view, name="detail_datasource"),
    path("datasources/<int:pk>/delete", views.DataSourceDeleteView.as_view(), name="delete_datasource"),
]

urlpatterns = [
    *datasets_urls,
    *datasource_urls,
]

data-platform-master/users/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
    path('logout/', auth_views.LogoutView.as_view(template_name='registration/logout.html'), name='logout'),
    path('', include('django.contrib.auth.urls')),
    path('signup/', views.Signup.as_view(), name='signup'),
]

data-platform-master/datasets/forms.py
import re

from django import forms
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator
from django.forms import inlineformset_factory

from datasets.services.conform_dataset import conform_dataset
from datasets.services.tags import save_tags

from .models import Dataset, DataSource, Column

TAG_INPUT_REGEX = r'^(?:[\w_0-9\.-]+)(?:\s*[\w_0-9\.-]+\s*)*$'
TAG_INPUT_FORMAT_MESSAGE = 'Tags should be space separated. Only letters, _ - and . are allowed.'


class CreateDatasetForm(forms.ModelForm):
    adding_tags = forms.CharField(label='Add tags',
                                  required=False,
                                  max_length=300,
                                  validators=[RegexValidator(regex=TAG_INPUT_REGEX, message=TAG_INPUT_FORMAT_MESSAGE)],
                                  widget=forms.HiddenInput())

    def __init__(self, *args, **kwargs):
        self.creator = kwargs.pop('user')
        super().__init__(*args, **kwargs)
        setattr(self.fields['adding_tags'], 'interactive_input', True)
        self.fields['data_source'].queryset = DataSource.objects.filter(creator=self.creator)

    class Meta:
        fields = ["title", "file", "description", 'is_public', 'data_source']
        model = Dataset
        widgets = {
            "description": forms.Textarea(),
        }

    def clean_adding_tags(self):
        return [] if not self.cleaned_data['adding_tags'] else set(re.split(r'\s+', self.cleaned_data['adding_tags']))

    def clean(self):
        cleaned_data = super().clean()
        dataset_title = cleaned_data['title']
        is_public = cleaned_data['is_public']
        data_source = cleaned_data['data_source']
        file = cleaned_data['file']
        if Dataset.objects.filter(is_public=is_public).filter(title=dataset_title):
            raise ValidationError('Dataset name already used!')
        try:
            conform_dataset(file, data_source)
        except Exception as exc:
            raise ValidationError(exc) from exc

    def save(self, commit=True):
        dataset = super().save(commit=False)
        dataset.creator = self.creator
        if commit:
            dataset.save()
            save_tags(self.cleaned_data['adding_tags'], dataset)
        return dataset


class UpdateDatasetForm(forms.ModelForm):
    adding_tags = forms.CharField(label='Add tags',
                                  required=False,
                                  max_length=300,
                                  validators=[
                                      RegexValidator(regex=TAG_INPUT_REGEX, message=TAG_INPUT_FORMAT_MESSAGE)],
                                  widget=forms.HiddenInput())
    deleting_tags = forms.ModelMultipleChoiceField(queryset=None,
                                                   required=False,
                                                   label='Select tags to delete',
                                                   widget=forms.CheckboxSelectMultiple)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        setattr(self.fields['adding_tags'], 'interactive_input', True)
        self.fields['deleting_tags'].queryset = self.instance.tags

    class Meta:
        model = Dataset
        fields = ['title', 'description']

    def clean_adding_tags(self):
        return [] if not self.cleaned_data['adding_tags'] else set(re.split(r'\s+', self.cleaned_data['adding_tags']))

    def clean(self):
        cleaned_data = super().clean()
        duplicate_tag = self.instance.tags.filter(text__in=cleaned_data.get('adding_tags', '')).first()
        if duplicate_tag:
            raise ValidationError(f'The tag {duplicate_tag} already exists in this dataset')

    def save(self, commit=True):
        dataset = super().save()
        if commit:
            dataset.save()
            dataset.tags.remove(*self.cleaned_data['deleting_tags'])
            save_tags(self.cleaned_data['adding_tags'], dataset)
        return dataset


class CreateDataSourceForm(forms.ModelForm):
    class Meta:
        fields = ["title", "description"]
        model = DataSource
        widgets = {
            "description": forms.Textarea(),
        }

    def save(self, creator, commit=True):
        datasource = super().save(commit=False)
        datasource.creator = creator
        datasource.save()
        return datasource

    def clean(self):
        cleaned_data = super().clean()
        title = cleaned_data['title']
        if DataSource.objects.filter(title=title):
            raise ValidationError('Data source name already used!')


TYPE_CHOICES = [
    ("int", "Integer"),
    ("object", "String"),
    ("bool", "Boolean"),
    ("float", "Floating point"),
    ("double", "Double"),
]


class ColumnForm(forms.ModelForm):
    type = forms.CharField(label='Column type', widget=forms.Select(choices=TYPE_CHOICES))

    class Meta:
        fields = ['title', 'type']
        model = Column

    def save(self, commit=True):
        column = super().save(commit=False)
        column.save()
        return column


ColumnsFormSet = inlineformset_factory(DataSource, Column, form=ColumnForm, extra=1, can_delete=False)

data-platform-master/datasets/views.py
import os
import operator
import re
from functools import reduce

from django.views.generic import CreateView, ListView, UpdateView, DeleteView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect, FileResponse, HttpResponseNotFound
from django.urls import reverse
from django.core.exceptions import PermissionDenied
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.http import QueryDict
from django.contrib import messages
from django.db.models import Q
from django.db.models import Count

from datasets.models import Dataset, Tag, DataSource
from datasets.services.read_csv import read_csv_dataset
from datasets.forms import CreateDatasetForm, UpdateDatasetForm, CreateDataSourceForm, ColumnsFormSet


def has_permission(permission_func):
    def decorator(func):
        def wrapper(*args, **kwargs):
            if permission_func(*args, **kwargs):
                return func(*args, **kwargs)
            raise PermissionDenied

        return wrapper

    return decorator


def has_dataset_owner_perm(request, pk):
    dataset = get_object_or_404(Dataset, pk=pk)
    return dataset.creator.id == request.user.id


class DataSourceCreateView(LoginRequiredMixin, CreateView):
    """
    Data Source create view in which column objects can be dynamically added to the data source-to-be-created
    """
    model = DataSource
    form_class = CreateDataSourceForm
    template_name = 'datasources/create.html'

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.object = None

    def get(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        column_form = ColumnsFormSet()
        return self.render_to_response(
            self.get_context_data(form=form,
                                  column_form=column_form))

    def post(self, request, *args, **kwargs):
        self.object = None
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        column_form = ColumnsFormSet(self.request.POST)
        if form.is_valid() and column_form.is_valid():
            return self.form_valid(form, column_form)
        return self.render_to_response(
            self.get_context_data(form=form,
                                  column_form=column_form))

    def form_valid(self, form, column_form):
        datasource = form.save(self.request.user)
        column_form.instance = datasource
        column_form.save()
        success_url = reverse("datasets:detail_datasource", args=(datasource.pk,))
        messages.success(self.request, 'Data source created successfully')
        return HttpResponseRedirect(success_url)


class DataSourceListView(LoginRequiredMixin, ListView):
    ITEMS_PER_PAGE = 10
    paginate_by = ITEMS_PER_PAGE
    template_name = "datasources/list.html"
    context_object_name = "datasources_list"

    def post(self, request):
        return super().get(request)

    def get_queryset(self):
        return DataSource.objects.filter(self.get_title_search_words_query(), creator=self.request.user)

    def get_title_search_words_query(self):
        query_list = [Q(title__icontains=search_word) for search_word in self.get_title_search_words()]
        return reduce(operator.or_, query_list, Q())

    def get_title_search_words(self):
        return re.split(r'\s+',
                        self.request.POST.get('search_box', '')) if 'search_box' in self.request.POST else []

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['searched'] = self.request.POST.get('search_box', '')
        context['url'] = 'datasources'
        return context


@login_required
def datasource_detail_view(request, pk):
    if request.method == 'GET':
        datasource = get_object_or_404(DataSource, pk=pk)
        context = {'datasource': datasource}
        return render(request, 'datasources/detail.html', context)
    return HttpResponse("Bad request!", status=400)


@method_decorator(login_required, name='dispatch')
class DataSourceDeleteView(DeleteView):
    model = DataSource
    template_name = 'datasources/datasource_confirm_delete.html'
    success_url = reverse_lazy('datasets:list_datasource')


class DatasetListView(LoginRequiredMixin, ListView):
    """datasets list view in which datasets can be filtered by their tags and searched by their titles"""
    ITEMS_PER_PAGE = 10
    paginate_by = ITEMS_PER_PAGE
    template_name = "datasets/datasets.html"
    context_object_name = "datasets_list"
    visibility = 'private'

    def post(self, request):
        return super().get(request)

    def get_queryset(self):
        if not self.get_applying_tags():
            return Dataset.objects.filter(
                self.get_title_search_words_query(), self.get_visibility_query(), self.get_creator_query())
        return Dataset.objects.filter(
            self.get_title_search_words_query(), self.get_visibility_query(), self.get_creator_query()).filter(
            tags__text__in=self.get_applying_tags()).distinct().annotate(
            matching_tags_no=Count('tags')).filter(
            matching_tags_no=len(self.get_applying_tags()))

    def get_visibility_query(self):
        return Q(is_public=True) if self.visibility == 'public' else Q(is_public=False)

    def get_creator_query(self):
        return Q() if self.visibility == 'public' else Q(creator=self.request.user)

    def get_applying_tags(self):
        return self.request.GET.getlist('tag')

    def get_title_search_words_query(self):
        query_list = [Q(title__icontains=search_word) for search_word in self.get_title_search_words()]
        return reduce(operator.or_, query_list, Q())

    def get_title_search_words(self):
        return re.split(r'\s+',
                        self.request.POST.get('search_box', '')) if 'search_box' in self.request.POST else []

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['visibility'] = self.visibility
        if self.visibility == 'public':
            context['url'] = 'public'
        if self.request.user.is_authenticated:
            context['inactive_tags'] = self.request.user.tags.exclude(text__in=self.request.GET.getlist('tag'))
        else:
            context['inactive_tags'] = Tag.objects.filter(datasets__is_public=True).exclude(
                text__in=self.request.GET.getlist('tag')).distinct()
        context['searched'] = self.request.POST.get('search_box', '')
        return context


class DatasetCreateView(LoginRequiredMixin, CreateView):
    model = Dataset
    form_class = CreateDatasetForm
    template_name = 'datasets/upload.html'

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        candidate = form.save(self.request.user)
        success_url = reverse("datasets:detail", args=(candidate.pk,))
        messages.success(self.request, 'Dataset created successfully')
        return HttpResponseRedirect(success_url)


@login_required
@has_permission(has_dataset_owner_perm)
def dataset_detail_view(request, pk):
    if request.method == 'GET':
        dataset = get_object_or_404(Dataset, pk=pk)
        context = {'csv': read_csv_dataset(str(dataset.file)),
                   'dataset': dataset}
        return render(request, 'datasets/detail.html', context)
    if request.method == 'PATCH':
        return handle_dataset_patch_method(request, pk)
    if request.method == 'DELETE':
        return handle_dataset_delete_method(pk)
    return HttpResponse("Bad request!", status=400)


def handle_dataset_patch_method(request, pk):
    data = QueryDict(request.body)
    dataset = get_object_or_404(Dataset, pk=pk)

    form = UpdateDatasetForm(data, instance=dataset)
    if not form.is_valid():
        return HttpResponse("Invalid format!", status=400)

    form.save()

    return HttpResponse(f"Dataset {pk} edited successfully", status=200)


def handle_dataset_delete_method(pk):
    dataset = get_object_or_404(Dataset, pk=pk)
    dataset.delete()
    return HttpResponse(f"Dataset {pk} deleted successfully", status=200)


@login_required
@has_permission(has_dataset_owner_perm)
def dataset_download_view(request, pk):
    dataset = get_object_or_404(Dataset, pk=pk)

    try:
        with open(dataset.file.path, 'r', encoding="utf-8") as file:
            file_data = file.read()
        response = FileResponse(file_data)
        response['Content-Disposition'] = f'attachment; filename="{dataset.file.name}"'
        return response
    except IOError:
        return HttpResponseNotFound('File not exist')


@method_decorator(has_permission(has_dataset_owner_perm), name='dispatch')
class DatasetUpdateView(LoginRequiredMixin, UpdateView):
    model = Dataset
    form_class = UpdateDatasetForm

    def get_success_url(self):
        return reverse('datasets:detail', args=(self.object.pk,))


@method_decorator(login_required, name='dispatch')
@method_decorator(has_permission(has_dataset_owner_perm), name='dispatch')
class DatasetDeleteView(DeleteView):
    model = Dataset
    success_url = reverse_lazy('datasets:index')

    def delete(self, request, *args, **kwargs):
        dataset = self.get_object()
        if dataset.file:
            if os.path.isfile(dataset.file.path):
                os.remove(dataset.file.path)
        return super().delete(self, request, *args, **kwargs)

data-platform-master/datasets/templates/datasets/dataset_confirm_delete.html
{% extends 'data_platform/basic.html' %}
{% load static %}

{% block head %}{% endblock %}

{% block title %}Delete Dataset{% endblock %}

{% block body %}


    <div class="ui center aligned page grid segment">
        <div class="delete_form_container">
            <h4>Are you sure you want to delete "{{ object }}"?</h4>
            <form method="post" class="ui form">
                {% csrf_token %}
                <br>
                <input type="submit" value="Yes, delete it" class="negative ui button">
                <a href="{% url 'datasets:detail' view.object.id %}" class="ui button">Cancel</a>
            </form>
        </div>
    </div>

{% endblock %}

data-platform-master/datasets/templates/datasets/dataset_content.html
<div style="width:100%; display: flex; justify-content: center; padding: 40px 60px 40px 60px;">
    <table class="ui celled teal table" style="max-width: 70%;">
        <thead>
        <tr>
            {% for h in csv.header %}
                <th>{{ h }}</th>
            {% endfor %}
        </tr>
        </thead>
        <tbody>
        {% for row in csv.rows %}
            <tr>
                {% for item in row %}
                    <td>{{ item }}</td>
                {% endfor %}
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

data-platform-master/datasets/templates/datasets/dataset_form.html
{% extends 'data_platform/basic.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static 'users/styles/basic_form.css' %}">
{% endblock %}

{% block title %}Edit Dataset{% endblock %}

{% block body %}


    <div class="ui center aligned page grid segment">
        <form method="post" class="ui form">
            {% csrf_token %}
            {% include 'registration/basic_form.html' with form=form title='Edit Dataset' submit_value="Submit" %}
        </form>
    </div>


{% endblock %}

data-platform-master/datasets/templates/datasets/dataset_info.html
<div class="about">
    <h4 style="align-self: flex-start; margin-top: -10px;"><a href="{% url 'datasets:index' %}">Back to list</a></h4>
    <a class="edit_link" href="{% url 'datasets:edit' dataset.id %}" data-tooltip="Edit this dataset">
        <i class="edit icon"></i>
    </a>

    <h3>About this dataset</h3>
    <h4>{{ dataset.title | title }}</h4>
    <h5> {{ dataset.description }}</h5>
{% if dataset.is_public == True %}
    <small>Public dataset</small>
{% else %}
    <small>Private dataset</small>
{% endif %}
    <br>
    <small>
        Created by:
        {% if dataset.creator.get_full_name %}
            {{ dataset.creator.get_full_name }}
        {% else %}
            {{ dataset.creator.username }}
        {% endif %}
    </small>
    <br>
    <small>Date Created: {{ dataset.date_created }}</small><br>
</div>

data-platform-master/datasets/templates/datasets/datasets.html
{% extends 'data_platform/basic.html' %}
{% load static %}

{% block head %}{% endblock %}

{% block title %}Datasets{% endblock %}

{% block body %}

    {% with url as url %}
        {% include 'datasets/search_bar.html' %}
    {% endwith %}

    {% if  datasets_list %}

        <h1>{{ visibility|title }} datasets:</h1>
        <br>

        <div class="ui relaxed divided list">
            {% for dataset in datasets_list reversed %}
                <div class="item">
                    <i class="large database middle aligned icon"></i>
                    <div class="content">
                        <a class="header" href="/datasets/{{ dataset.id }}/">{{ dataset.title }}</a>
                        <div class="description">Created at {{ dataset.date_created }}</div>
                    </div>
                </div>
            {% endfor %}
        </div>

        <br>

        {% include 'data_platform/pagination.html' %}

    {% else %}
        <h2>No {{ visibility }} datasets available.</h2>
    {% endif %}

    <br>

    <a href="{% url 'datasets:upload' %}">upload a new file?</a>


{% endblock %}

data-platform-master/datasets/templates/datasets/detail.html
{% extends 'data_platform/basic.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static 'datasets/styles/detail.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
{% endblock %}

{% block title %}Dataset Details{% endblock %}

{% block body %}

    {% include "datasets/dataset_info.html" %}
    {% include "datasets/dataset_content.html" %}

    <a href="{% url 'datasets:download' pk=dataset.id %}" class="ui labeled icon button">
        <i class="download icon"></i>
        Download
    </a>
    <a href="{% url 'datasets:delete' pk=dataset.id %}" class="ui negative button">
        Delete
    </a>
    {% if dataset.tags.all %}
        <div style="font-style: italic; margin-top: 20px;">
            Tags:
            {% for tag in dataset.tags.all %}
                {% if dataset.is_public == True %}
                    <a class="ui medium label" style="margin-top: 5px;"
                       href="{% url 'datasets:public' %}?tag={{ tag.text }}">{{ tag.text }}</a>
                {% else %}
                    <a class="ui medium label" style="margin-top: 5px;"
                       href="{% url 'datasets:index' %}?tag={{ tag.text }}">{{ tag.text }}</a>
                {% endif %}

            {% endfor %}
        </div>
    {% endif %}

{% endblock %}

data-platform-master/datasets/templates/datasets/filter_bar.html
{% load static %}
{% load filter_query_params %}


{% get_tag_params request as active_tags %}

<div class="ui segment" id="filter_bar">
    <h3>Select tags to apply filter:</h3>
    {% if inactive_tags or active_tags %}
        <form action="{% url 'datasets:index' %}" method="post" class="tags_container">
            {% csrf_token %}
            {% for a_tag in active_tags %}
                <a href="{% remove_tag_param request a_tag %}" class="ui medium blue label"
                   style="margin-top: 5px;">{{ a_tag }}</a>
            {% endfor %}
            {% for i_tag in inactive_tags %}
                <a href="{% add_tag_param request i_tag %}" class="ui medium label"
                   style="margin-top: 5px;">{{ i_tag }}</a>
            {% endfor %}
        </form>
    {% else %}
        <small>You dont have any tags yet.</small>
    {% endif %}
</div>

data-platform-master/datasets/templates/datasets/search_bar.html
{% load static %}

<script>
    const filterBarHtmlString = `{% include 'datasets/filter_bar.html' %}`
</script>
<script src="{% static 'datasets/scripts/search_bar.js' %}"></script>

<form action="{% url 'datasets:index' %}{{ url }}?{{ request.GET.urlencode }}" method="post" id="search_bar">
    {% csrf_token %}
    <div class="ui menu">
        <div class="ui category search item">
            <div class="ui transparent icon input">
                <input class="prompt" type="text" placeholder="Search ..." name="search_box">
                <i class="search link icon"></i>
            </div>
            <div class="results"></div>
        </div>
        <div style="width: 100%;"></div>
        <div style="margin: 10px; display: flex;" data-tooltip="Filter">
            <i class="angle right link icon" onclick="toggleFilterBar(this)"></i>
        </div>
    </div>
</form>

data-platform-master/datasets/templates/datasets/upload.html
{% extends 'data_platform/basic.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static 'users/styles/basic_form.css' %}">
{% endblock %}

{% block title %}Upload Dataset{% endblock %}

{% block body %}


    <div class="ui center aligned page grid segment">
        <form enctype="multipart/form-data" action="{% url 'datasets:upload' %}" method="post" class="ui form">
            {% csrf_token %}
            {% include 'registration/basic_form.html' with form=form title='Upload a new file' submit_value='Submit' %}
        </form>

    </div>

{% endblock %}